# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot = {
    initrd = {
      availableKernelModules = [
      "ata_piix"
      "ohci_pci" 
      "ehci_pci" 
      "ahci" 
      "sd_mod" 
      "sr_mod"
      ];
      kernelModules = [ ];
    };
    kernelModules = [ ];
    extraModulePackages = [ ];
    # kernelParams = [
    #   "systemd.mask=systemd-vconsole-setup.service"
    #   "systemd.mask=dev-tpmrm0.device"
    # ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4ccb0c2a-a0ae-4e9d-b1fb-03add02f2df0";
      fsType = "ext4";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s3.useDHCP = lib.mkDefault true;
  hardware.pulseaudio.enable = false;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  virtualisation.virtualbox.guest.enable = true;
}
